### ISSUE TITLE
clearing disabled channels does not clear X's in observe tab

### ISSUE THREAD

**Issue by ggggggggg** [usnistgov/dastardcommander#112]
See video for demonstration of bug. When I clear the disabled channels I expect the Xs on the observe tab to clear and for it to return to showing the trigger rate. 

https://share.vidyard.com/watch/wgkL4St5NzuqrQnbEyj9DL?

**Comment by joefowler** [comment]
Huh. I am sure I tested something like this, so I'm mystified. Anyway, when I test it, I can definitely reproduce what that video shows, so I'll work on it.

[Aside: you were surprised that channels 3-4 went to zero rate when you clicked to disable channels 1-2. That is the expected result of the way that we always reset the trigger rate integration whenever trigger conditions are changed. We aren't used to noticing this, however, because this is the first time that we have a way to change conditions while the Observe Tab is visible!]
